# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detrend.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_detrend(object):
    def setupUi(self, detrend):
        detrend.setObjectName("detrend")
        detrend.resize(409, 328)
        font = QtGui.QFont()
        font.setPointSize(10)
        detrend.setFont(font)
        self.label = QtWidgets.QLabel(detrend)
        self.label.setGeometry(QtCore.QRect(60, 20, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.valorQ = QtWidgets.QComboBox(detrend)
        self.valorQ.setGeometry(QtCore.QRect(130, 20, 181, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.valorQ.setFont(font)
        self.valorQ.setObjectName("valorQ")
        self.valorQ.addItem("")
        self.valorQ.addItem("")
        self.valorQ.addItem("")
        self.valorQ.addItem("")
        self.valorQ.addItem("")
        self.valorQ.addItem("")
        self.escalas = QtWidgets.QComboBox(detrend)
        self.escalas.setGeometry(QtCore.QRect(130, 120, 181, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.escalas.setFont(font)
        self.escalas.setObjectName("escalas")
        self.escalas.addItem("")
        self.escalas.addItem("")
        self.escalas.addItem("")
        self.escalas.addItem("")
        self.escalas.addItem("")
        self.label_2 = QtWidgets.QLabel(detrend)
        self.label_2.setGeometry(QtCore.QRect(60, 170, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btnCodificanteA = QtWidgets.QPushButton(detrend)
        self.btnCodificanteA.setGeometry(QtCore.QRect(40, 230, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnCodificanteA.setFont(font)
        self.btnCodificanteA.setObjectName("btnCodificanteA")
        self.label_6 = QtWidgets.QLabel(detrend)
        self.label_6.setGeometry(QtCore.QRect(60, 120, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalSlider = QtWidgets.QSlider(detrend)
        self.horizontalSlider.setGeometry(QtCore.QRect(130, 170, 161, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.horizontalSlider.setFont(font)
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(4)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.lblGrado = QtWidgets.QLabel(detrend)
        self.lblGrado.setGeometry(QtCore.QRect(310, 170, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblGrado.setFont(font)
        self.lblGrado.setObjectName("lblGrado")
        self.btnNoCodificanteA = QtWidgets.QPushButton(detrend)
        self.btnNoCodificanteA.setGeometry(QtCore.QRect(220, 230, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnNoCodificanteA.setFont(font)
        self.btnNoCodificanteA.setObjectName("btnNoCodificanteA")
        self.label_3 = QtWidgets.QLabel(detrend)
        self.label_3.setGeometry(QtCore.QRect(60, 60, 91, 31))
        self.label_3.setObjectName("label_3")
        self.distancia = QtWidgets.QTextEdit(detrend)
        self.distancia.setGeometry(QtCore.QRect(150, 60, 161, 31))
        self.distancia.setObjectName("distancia")
        self.btnAmbas = QtWidgets.QPushButton(detrend)
        self.btnAmbas.setGeometry(QtCore.QRect(160, 280, 91, 31))
        self.btnAmbas.setObjectName("btnAmbas")

        self.retranslateUi(detrend)
        self.horizontalSlider.sliderMoved['int'].connect(self.lblGrado.setNum)
        QtCore.QMetaObject.connectSlotsByName(detrend)

    def retranslateUi(self, detrend):
        _translate = QtCore.QCoreApplication.translate
        detrend.setWindowTitle(_translate("detrend", "Detrend"))
        self.label.setText(_translate("detrend", "Valor q:"))
        self.valorQ.setItemText(0, _translate("detrend", "Seleccione una Opción"))
        self.valorQ.setItemText(1, _translate("detrend", "-1 a 1"))
        self.valorQ.setItemText(2, _translate("detrend", "-3 a 3"))
        self.valorQ.setItemText(3, _translate("detrend", "-5 a 5"))
        self.valorQ.setItemText(4, _translate("detrend", "-10 a 10"))
        self.valorQ.setItemText(5, _translate("detrend", "-20 a 20"))
        self.escalas.setItemText(0, _translate("detrend", "Seleccione una Opcion"))
        self.escalas.setItemText(1, _translate("detrend", "5"))
        self.escalas.setItemText(2, _translate("detrend", "10"))
        self.escalas.setItemText(3, _translate("detrend", "20"))
        self.escalas.setItemText(4, _translate("detrend", "50"))
        self.label_2.setText(_translate("detrend", "Grado:"))
        self.btnCodificanteA.setText(_translate("detrend", "Analsis Codificante"))
        self.label_6.setText(_translate("detrend", "Escalas:"))
        self.lblGrado.setText(_translate("detrend", "1"))
        self.btnNoCodificanteA.setText(_translate("detrend", "Analsis No Codificante"))
        self.label_3.setText(_translate("detrend", "Distancia de q:"))
        self.btnAmbas.setText(_translate("detrend", "Ambas"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    detrend = QtWidgets.QWidget()
    ui = Ui_detrend()
    ui.setupUi(detrend)
    detrend.show()
    sys.exit(app.exec_())
